/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type Testimonial = {
  _type: 'testimonial';
  quote?: InternationalizedArrayText;
  authorName?: InternationalizedArrayString;
  authorRole?: InternationalizedArrayString;
};

export type Pillar = {
  _type: 'pillar';
  title?: InternationalizedArrayString;
  body?: InternationalizedArrayText;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nav?: {
    approachLabel?: InternationalizedArrayString;
    contactLabel?: InternationalizedArrayString;
  };
  hero?: {
    headline?: InternationalizedArrayString;
    subtitle?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    ctaText?: InternationalizedArrayString;
    ctaUrl?: string;
  };
  video?: {
    url?: string;
  };
  approach?: {
    heading?: InternationalizedArrayString;
    intro?: InternationalizedArrayText;
    pillars?: Array<
      {
        _key: string;
      } & Pillar
    >;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    imageAlt?: InternationalizedArrayString;
  };
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  contact?: {
    heading?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    formHeading?: InternationalizedArrayString;
    formBody?: InternationalizedArrayText;
    labelName?: InternationalizedArrayString;
    labelOrg?: InternationalizedArrayString;
    labelEmail?: InternationalizedArrayString;
    labelMessage?: InternationalizedArrayString;
    submitText?: InternationalizedArrayString;
    successMessage?: InternationalizedArrayText;
    errorMessage?: InternationalizedArrayText;
    email?: string;
    phone?: string;
    linkedinUrl?: string;
    labelWorkshops?: InternationalizedArrayString;
    labelDirect?: InternationalizedArrayString;
    labelLinkedin?: InternationalizedArrayString;
  };
  footer?: {
    marqueeText?: InternationalizedArrayString;
    copyright?: InternationalizedArrayString;
  };
  seo?: {
    title?: InternationalizedArrayString;
    description?: InternationalizedArrayText;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue';
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Testimonial
  | Pillar
  | SanityImageAssetReference
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayText
  | InternationalizedArrayString
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/lib/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]
export type HomePageQueryResult = {
  _id: 'homePage';
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nav?: {
    approachLabel?: InternationalizedArrayString;
    contactLabel?: InternationalizedArrayString;
  };
  hero?: {
    headline?: InternationalizedArrayString;
    subtitle?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    ctaText?: InternationalizedArrayString;
    ctaUrl?: string;
  };
  video?: {
    url?: string;
  };
  approach?: {
    heading?: InternationalizedArrayString;
    intro?: InternationalizedArrayText;
    pillars?: Array<
      {
        _key: string;
      } & Pillar
    >;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
    imageAlt?: InternationalizedArrayString;
  };
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  contact?: {
    heading?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    formHeading?: InternationalizedArrayString;
    formBody?: InternationalizedArrayText;
    labelName?: InternationalizedArrayString;
    labelOrg?: InternationalizedArrayString;
    labelEmail?: InternationalizedArrayString;
    labelMessage?: InternationalizedArrayString;
    submitText?: InternationalizedArrayString;
    successMessage?: InternationalizedArrayText;
    errorMessage?: InternationalizedArrayText;
    email?: string;
    phone?: string;
    linkedinUrl?: string;
    labelWorkshops?: InternationalizedArrayString;
    labelDirect?: InternationalizedArrayString;
    labelLinkedin?: InternationalizedArrayString;
  };
  footer?: {
    marqueeText?: InternationalizedArrayString;
    copyright?: InternationalizedArrayString;
  };
  seo?: {
    title?: InternationalizedArrayString;
    description?: InternationalizedArrayText;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "homePage" && _id == "homePage"][0]': HomePageQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
