import { HomeIcon } from '@sanity/icons';
import { defineField, defineType } from 'sanity';

export const homePage = defineType({
  name: 'homePage',
  title: 'Homepage',
  type: 'document',
  icon: HomeIcon,
  groups: [
    { name: 'nav', title: 'Navigation', default: true },
    { name: 'hero', title: 'Hero' },
    { name: 'video', title: 'Video' },
    { name: 'approach', title: 'Approach' },
    { name: 'testimonials', title: 'Testimonials' },
    { name: 'contact', title: 'Contact' },
    { name: 'footer', title: 'Footer' },
  ],
  fields: [
    defineField({
      name: 'navApproach',
      title: 'Approach link label',
      type: 'internationalizedArrayString',
      group: 'nav',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'navContact',
      title: 'Contact link label',
      type: 'internationalizedArrayString',
      group: 'nav',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Headline',
      type: 'internationalizedArrayString',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Subtitle',
      type: 'internationalizedArrayString',
      group: 'hero',
    }),
    defineField({
      name: 'heroBody',
      title: 'Body',
      type: 'internationalizedArrayText',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroCtaText',
      title: 'CTA text',
      type: 'internationalizedArrayString',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroCtaUrl',
      title: 'CTA URL',
      type: 'string',
      group: 'hero',
      initialValue: '#contacto',
    }),
    defineField({
      name: 'videoUrl',
      title: 'Embed URL',
      type: 'url',
      group: 'video',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'approachHeading',
      title: 'Heading',
      type: 'internationalizedArrayString',
      group: 'approach',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'approachIntro',
      title: 'Intro',
      type: 'internationalizedArrayText',
      group: 'approach',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'approachPillars',
      title: 'Pillars',
      type: 'array',
      group: 'approach',
      of: [{ type: 'pillar' }],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({
      name: 'approachImage',
      title: 'Image path',
      description: 'Path under /public, e.g. /images/enfoque.jpg',
      type: 'string',
      group: 'approach',
      initialValue: '/images/enfoque.jpg',
    }),
    defineField({
      name: 'approachImageAlt',
      title: 'Image alt text',
      type: 'internationalizedArrayString',
      group: 'approach',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'testimonials',
      title: 'Testimonials',
      type: 'array',
      group: 'testimonials',
      of: [{ type: 'testimonial' }],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({
      name: 'contactHeading',
      title: 'Heading',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactBody',
      title: 'Body',
      type: 'internationalizedArrayText',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactFormHeading',
      title: 'Form heading',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactFormBody',
      title: 'Form body',
      type: 'internationalizedArrayText',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelName',
      title: 'Name label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelOrg',
      title: 'Organisation label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelEmail',
      title: 'Email label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelMessage',
      title: 'Message label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactSubmitText',
      title: 'Submit button',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactEmail',
      title: 'Email address',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: 'contactPhone',
      title: 'Phone number',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLinkedinUrl',
      title: 'LinkedIn URL',
      type: 'url',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelWorkshops',
      title: 'Workshops label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelDirect',
      title: 'Direct contact label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactLabelLinkedin',
      title: 'LinkedIn label',
      type: 'internationalizedArrayString',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'footerMarqueeText',
      title: 'Marquee text',
      type: 'internationalizedArrayString',
      group: 'footer',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Copyright',
      type: 'internationalizedArrayString',
      group: 'footer',
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Homepage' };
    },
  },
});
